name: "CI/CD"
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: publish
        run: ls